### ISSUE TITLE
start.bat errors

### ISSUE THREAD

**Issue by plusmaa** [KWich/MyMediathek#1]
Hi, das Projekt klingt sehr vielversprechend.
Ich habe aber ein Problem beim Öffnen der start.bat unter Windows. Wenn ich sie per Doppelklick öffne, schließt sich das CMD-Fenster sofort wieder. Wenn ich versuche, sie über CMD zu öffnen, erhalte ich folgende Meldung:

```
C:\myMediathek-win>start.bat
Starte MyMediathek 0.9.0 (02/01/2023)
- Python ist installiert
- PIP ist installiert
- Python environment existiert
- Environment wird aktiviert
- Server wird gestartet
Traceback (most recent call last):
  File "C:\myMediathek-win\src\main.py", line 12, in <module>
    from api import connex_app, db, dbname, cfgConfig
  File "C:\myMediathek-win\src\api\__init__.py", line 2, in <module>
    import connexion
ModuleNotFoundError: No module named 'connexion'
'deactivate' is not recognized as an internal or external command,
operable program or batch file.
(env) C:\myMediathek-win>
```

**Comment by KWich** [comment]
Auf den ersten Blick sieht es so aus als ob beim Erstellen des Python Environments was schiefgegangen ist.  Sie können das mal kontrollieren indem Sie das Environment von Hand aktivieren und die Liste der installierten Pakete anzeigen
> C:\myMediathek-win>**env\Scripts\activate**
>(env) C:\myMediathek-win>**pip3 list**
>Package                Version
>  ---------------------- ---------
>attrs                  22.2.0
>certifi                2022.12.7
>charset-normalizer     2.1.1
>click                  8.1.3
>clickclick             20.10.2
>colorama               0.4.6
>connexion              2.14.1
>Flask                  2.2.2
>Flask-Cors             3.0.10
>flask-marshmallow      0.14.0
>Flask-SQLAlchemy       3.0.2
>greenlet               2.0.1
>gunicorn               20.1.0
>idna                   3.4
>importlib-metadata     6.0.0
>importlib-resources    5.10.2
>inflection             0.5.1
>itsdangerous           2.1.2
>Jinja2                 3.1.2
>jsonschema             4.17.3
>MarkupSafe             2.1.1
>marshmallow            3.19.0
>marshmallow-sqlalchemy 0.28.1
>packaging              22.0
>pip                    19.2.3
>pkgutil-resolve-name   1.3.10
>pyrsistent             0.19.3
>python-dateutil        2.8.2
>python-dotenv          0.21.0
>PyYAML                 6.0
>requests               2.28.1
>setuptools             41.2.0
>six                    1.16.0
>SQLAlchemy             1.4.46
>swagger-ui-bundle      0.0.9
>urllib3                1.26.13
>Werkzeug               2.2.2
>zipp                   3.11.0

Wenn was fehlt einfach nachinstallieren mit:
> (env) C:\myMediathek-win>pip3 install -r scripts/python-requirements

(Environment muss aktiv sein)
